package edu.gatech.cs6400.Backend.beans;

import lombok.Data;

@Data	//The annotation in lombok used to generate getters and setters
public class City {
	
	private String city;
	private String state_name;
	private int population;

	//Below: constructors 
	public City(String city, String state_name, int population) {
		super();
		this.city = city;
		this.state_name = state_name;
		this.population = population;
	}
	public City() { // this is the default constructor that will automatically generated by the compiler if no other constructor is present
		//here since we defined a constructor above, we must add this default constructor by hand. Otherwise there will be problem.
		super();
	}
// Below: getter and setters that are generated automatically by the @Data annotation.
// You do NOT need to writer getters and setters

//	public String getCity() {
//		return city;
//	}
//	public void setCity(String city) {
//		this.city = city;
//	}
//	public String getState_name() {
//		return state_name;
//	}
//	public void setState_name(String state_name) {
//		this.state_name = state_name;
//	}
//	public int getPopulation() {
//		return population;
//	}
//	public void setPopulation(int population) {
//		this.population = population;
//	}
	
	
	

}
